### ISSUE TITLE
Example required

### ISSUE THREAD

**Issue by sergeevabc** [AyrA/fcfh#1]
Dear @AyrA, the documentation has no real life example on how to use the app.
Could you be so kind to add one? e.g. ```fcfh.exe /e …```

**Comment by AyrA** [comment]
The application is very easy to use and examples should not be necessary as the full command line help is contained in the readme file as well as the application itself. [The help syntax is as outlined by Microsoft](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key).

Most basic usage:

- Encode as pixels (creates new file): `fcfh /e input.file`
- Same as previous but specify a custom PNG file name: `fcfh /e input.file output.png`
- Encode into header (requires existing file): `fcfh /e some.file output.png /header existing.png`
- Decode from an image (output file name is recovered): `fcfh /d encoded.png`

Adding `/p` will encrypt the file when encoding and decrypt when decoding. You're prompted for a password at runtime.

## This is a dual mode application

This application can be used from a terminal as well as via graphical user interface. If terminal usage is too troublesome for you, you can use UI mode instead. This application only launches in terminal mode if it thinks you're in a terminal or you supplied arguments. Just double click the application to open it in UI mode. The UI has a few advantages over the terminal mode, specifically it auto detects if a file was encrypted and needs a password, it can also decode multiple files that are in a single PNG. The terminal will only decode the first file it finds.

The only thing the UI will not do is encode bare strings into an image (see `/s` argument in the help)
